//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int Part_ID { get; set; }
        public string Part_Description { get; set; }
        public decimal Part_UnitPrice { get; set; }
        public int Part_QtyOnHand { get; set; }
        public decimal Part_StockValue { get; set; }
        public System.DateTime Part_AddedDate { get; set; }
    }
}
